# Generated by Django 5.2.8 on 2026-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cuentas_permitidas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
