# Generated by Django 5.2.8 on 2025-11-21 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_ap2_alter_paciente_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El teléfono debe contener solo números.', regex='^\\d{8}$')]),
        ),
    ]
