# Generated by Django 5.2.8 on 2026-04-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('pa', 'Paciente'), ('de', 'Dentista')], default='pa', max_length=12),
        ),
    ]
