# Generated by Django 5.2.8 on 2025-11-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
