# Generated by Django 5.2.8 on 2026-03-16 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default=0, max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_number', message='El teléfono debe contener solo números.', regex='^\\d{8}$')]),
        ),
    ]
