# Generated by Django 5.2.8 on 2026-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('pa', 'Paciente'), ('de', 'Dentista'), ('ad', 'Administrador')], default='pa', max_length=12),
        ),
    ]
