# Generated by Django 5.2.8 on 2026-03-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_paciente_es_menor_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='es_menor',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
