# Generated by Django 5.2.8 on 2026-03-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.estadocita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.tipocita'),
        ),
    ]
