# Generated by Django 5.2.7 on 2025-11-15 00:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
        ('dentista', '0001_initial'),
        ('paciente', '0002_alter_paciente_ap2_alter_paciente_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='actualizada',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='creada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dentista.dentista'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.estadocita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.tipocita'),
        ),
    ]
