# Generated by Django 5.2.8 on 2026-03-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocita',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
