# Generated by Django 5.2.8 on 2025-11-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_estadocita_tipocita_cita_actualizada_cita_creada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default='10:00'),
        ),
    ]
