# Generated by Django 5.2.8 on 2025-11-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_alter_cita_hora'),
        ('dentista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentista.dentista'),
        ),
    ]
