# Generated by Django 5.2.8 on 2026-03-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_tipocita_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='precio_cita',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
