# Generated by Django 5.2.8 on 2026-03-22 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_cita_precio_cita'),
        ('paciente', '0003_alter_paciente_telefono'),
        ('tratamientos', '0002_tipotratamiento_precio_estimado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeticionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('estado_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.estadocita')),
                ('paciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('tratamiento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.plantratamiento')),
            ],
        ),
    ]
