# Generated by Django 5.2.8 on 2026-04-05 03:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0005_peticioncita'),
        ('paciente', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peticioncita',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='peticioncita',
            name='tipo_cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.tipocita'),
        ),
        migrations.AlterField(
            model_name='peticioncita',
            name='estado_cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.estadocita'),
        ),
        migrations.AlterField(
            model_name='peticioncita',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.CreateModel(
            name='Notificacion_Notificacion_Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField()),
                ('titulo', models.CharField(null=True)),
                ('creada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_cita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
                ('fk_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('fk_peticion_cita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cita.peticioncita')),
            ],
        ),
    ]
