# Generated by Django 5.2.8 on 2026-04-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0006_remove_peticioncita_tratamiento_and_more'),
        ('tratamientos', '0006_remove_itemsesion_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='itemsesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='tratamientos.itemsesion'),
        ),
    ]
