# Generated by Django 5.2.8 on 2025-11-19 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0003_alter_cita_hora'),
        ('dentista', '0001_initial'),
        ('paciente', '0002_alter_paciente_ap2_alter_paciente_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Proceso'), ('C', 'Completado')], default='P', max_length=1)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True, null=True)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias', to='tratamientos.planitems')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True, null=True)),
                ('cita', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
                ('plan_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.planitems')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complejidad', models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='B', max_length=1)),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Proceso'), ('C', 'Completado')], default='P', max_length=1)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True, null=True)),
                ('dentista', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dentista.dentista')),
                ('paciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('tratamiento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.tipotratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='planitems',
            name='plan_tratamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.plantratamiento'),
        ),
    ]
