# Generated by Django 5.2.8 on 2026-03-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
        ('dentista', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Proceso'), ('C', 'Completado')], default='P', max_length=1)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True, null=True)),
                ('cita', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.cita')),
                ('plan_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.planitems')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('C', 'Cancelado'), ('E', 'En Proceso'), ('T', 'Completado')], default='E', max_length=1)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True, null=True)),
                ('precio_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dentista', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dentista.dentista')),
                ('paciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('tratamiento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.tipotratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='planitems',
            name='plan_tratamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='tratamientos.plantratamiento'),
        ),
    ]
