# Generated by Django 5.2.8 on 2026-03-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotratamiento',
            name='precio_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
