# Generated by Django 5.2.8 on 2025-11-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsesion',
            name='numero_sesion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='planitems',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
