# Generated by Django 5.2.8 on 2025-11-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0002_itemsesion_numero_sesion_planitems_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantratamiento',
            name='estado',
            field=models.CharField(choices=[('C', 'Cancelado'), ('E', 'En Proceso'), ('C', 'Completado')], default='E', max_length=1),
        ),
    ]
