# Generated by Django 5.2.8 on 2026-04-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0002_tipotratamiento_precio_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsesion',
            name='plan_item',
        ),
        migrations.AddField(
            model_name='itemsesion',
            name='plan_tratamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.plantratamiento'),
        ),
        migrations.AddField(
            model_name='plantratamiento',
            name='sesiones_estimadas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='plantratamiento',
            name='sesiones_realizadas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='PlanItems',
        ),
    ]
