# Generated by Django 5.2.8 on 2026-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_remove_itemsesion_plan_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsesion',
            name='nombre_sesion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
