# Generated by Django 5.2.8 on 2025-11-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_alter_plantratamiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantratamiento',
            name='estado',
            field=models.CharField(choices=[('C', 'Cancelado'), ('E', 'En Proceso'), ('T', 'Completado')], default='E', max_length=1),
        ),
    ]
