# Generated by Django 5.2.8 on 2025-11-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0004_alter_plantratamiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitems',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
