# Generated by Django 5.2.8 on 2026-04-05 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0006_remove_peticioncita_tratamiento_and_more'),
        ('tratamientos', '0004_itemsesion_nombre_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsesion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.cita'),
        ),
        migrations.AlterField(
            model_name='itemsesion',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.plantratamiento'),
        ),
    ]
