# Generated by Django 5.2.8 on 2026-04-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0005_alter_itemsesion_cita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsesion',
            name='cita',
        ),
        migrations.AlterField(
            model_name='itemsesion',
            name='plan_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='tratamientos.plantratamiento'),
        ),
    ]
