# Generated by Django 5.2.8 on 2025-11-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0005_alter_planitems_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitems',
            name='dependencia',
        ),
    ]
