# Generated by Django 5.2.8 on 2025-11-21 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0006_remove_planitems_dependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsesion',
            name='numero_sesion',
        ),
        migrations.AlterField(
            model_name='planitems',
            name='plan_tratamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='tratamientos.plantratamiento'),
        ),
    ]
