# Generated by Django 5.2.8 on 2026-03-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0007_remove_itemsesion_numero_sesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantratamiento',
            name='precio_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
