# Generated by Django 5.2.8 on 2026-03-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0008_plantratamiento_precio_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantratamiento',
            name='complejidad',
        ),
    ]
