# Generated by Django 5.2.8 on 2026-03-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb1', models.CharField(max_length=30)),
                ('nb2', models.CharField(blank=True, max_length=30, null=True)),
                ('ap1', models.CharField(max_length=30)),
                ('ap2', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cedula', models.CharField(default='', max_length=16, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
