# Generated by Django 5.2.8 on 2025-11-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
