# Generated by Django 5.2.8 on 2025-11-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentista', '0002_dentista_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='cedula',
            field=models.CharField(default='', max_length=14),
        ),
    ]
