# Generated by Django 5.2.8 on 2025-11-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentista', '0004_alter_dentista_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='cedula',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
